### ISSUE TITLE
Exception Handling

### ISSUE THREAD

**Issue by rabeUni** [HalgrimThadeus/long-read-microbiome#10]
Which exceptions should we throw  and which should be handled inside the IO_classes?

**Comment by canerbagci** [comment]
Generally speaking, throw those for which you know explicitly why it has happened (e.g. file does not exists); so that you can print nice error messages later in the GUI.

Also, two more things about exception handling:
- Never use System.out, use System.err instead if you want to print error/log messages.
- Please print the stack trace and not only custom error messages.

Have a look at Logger, too. https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html
